version: "3.8"
services:
  app:
    build: .
    ports:
      - 9010:9010
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:10.16
    environment:      
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  db-data:
